name: Pull request validation

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci -ignore-scripts
      - name: Lint
        run: npm run lint
      - name: Build code
        run: npm run build:ci
      - name: Test code
        run: npm run test
